/**
 * Represents the response structure for creating a Plaid Link Token.
 */
export interface LinkTokenResponse {
  // The link token generated by Plaid
  // and used to initialize the Plaid Link widget
  link_token: string;
}

/**
 * Represents the request structure for exchanging a public token
 * with an access token using Plaid's exchange token endpoint.
 */
export interface PublicTokenRequest {
  // The public token provided by the frontend
  // after the user completes the Plaid Link flow.
  public_token: string;
}

/**
 * Represents the request structure for exchanging a public token
 * with an access token using Plaid's API.
 */
export interface PublicTokenExchangeResponse {
  // The access token returned by Plaid
  access_token: string;

  // The item ID associated with the Plaid Item (a collection of accounts)
  item_id: string;
}
